version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9092:9092
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./monitoring/recording_rules.yml:/etc/prometheus/recording_rules.yml
      - ./monitoring/dynamic_targets.json:/etc/prometheus/dynamic_targets.json
  promlens:
    image: prom/promlens
    ports:
      - 8080:8080
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager/alertmanager.yml:/config/alertmanager.yml"
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  consul-server:
    image: hashicorp/consul:1.11.2
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
  consul-exporter:
    image: prom/consul-exporter
    ports:
      - "9107:9107"
    command: --consul.server=consul-server:8500
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped